// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using NimbusApi.Connection;
using Oracle.EntityFrameworkCore.Metadata;

#nullable disable

namespace NimbusApi.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20250605215549_SegundaMigration")]
    partial class SegundaMigration
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            OracleModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("NimbusApi.Models.Alerta", b =>
                {
                    b.Property<int>("IdAlerta")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(10)");

                    OraclePropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdAlerta"));

                    b.Property<DateTime>("DataHora")
                        .HasColumnType("TIMESTAMP(7)");

                    b.Property<string>("Descricao")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("NVARCHAR2(200)");

                    b.Property<int>("IdBairro")
                        .HasColumnType("NUMBER(10)");

                    b.Property<string>("Mensagem")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("NVARCHAR2(500)");

                    b.Property<string>("Risco")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("NVARCHAR2(50)");

                    b.HasKey("IdAlerta");

                    b.HasIndex("IdBairro");

                    b.ToTable("t_nimbus_alerta", (string)null);
                });

            modelBuilder.Entity("NimbusApi.Models.Bairro", b =>
                {
                    b.Property<int>("IdBairro")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(10)")
                        .HasColumnName("id_bairro");

                    OraclePropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdBairro"));

                    b.Property<int>("IdCidade")
                        .HasColumnType("NUMBER(10)");

                    b.Property<int>("IdLocalizacao")
                        .HasColumnType("NUMBER(10)");

                    b.Property<string>("Logradouro")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("NVARCHAR2(100)");

                    b.HasKey("IdBairro");

                    b.HasIndex("IdCidade");

                    b.HasIndex("IdLocalizacao");

                    b.ToTable("t_nimbus_bairro", (string)null);
                });

            modelBuilder.Entity("NimbusApi.Models.Cidade", b =>
                {
                    b.Property<int>("IdCidade")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(10)")
                        .HasColumnName("id_cidade");

                    OraclePropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdCidade"));

                    b.Property<int>("IdEstado")
                        .HasColumnType("NUMBER(10)");

                    b.Property<string>("NomeCidade")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("NVARCHAR2(100)");

                    b.HasKey("IdCidade");

                    b.HasIndex("IdEstado");

                    b.ToTable("t_nimbus_cidade", (string)null);
                });

            modelBuilder.Entity("NimbusApi.Models.Endereco", b =>
                {
                    b.Property<int>("IdEndereco")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(10)")
                        .HasColumnName("id_endereco");

                    OraclePropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdEndereco"));

                    b.Property<string>("Cep")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("NVARCHAR2(10)")
                        .HasColumnName("cep");

                    b.Property<int>("IdBairro")
                        .HasColumnType("NUMBER(10)")
                        .HasColumnName("id_bairro");

                    b.HasKey("IdEndereco");

                    b.HasIndex("IdBairro");

                    b.ToTable("t_nimbus_endereco", (string)null);
                });

            modelBuilder.Entity("NimbusApi.Models.Estado", b =>
                {
                    b.Property<int>("IdEstado")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(10)")
                        .HasColumnName("id_estado");

                    OraclePropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdEstado"));

                    b.Property<int>("IdPais")
                        .HasColumnType("NUMBER(10)");

                    b.Property<string>("NomeEstado")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("NVARCHAR2(100)");

                    b.HasKey("IdEstado");

                    b.HasIndex("IdPais");

                    b.ToTable("t_nimbus_estado", (string)null);
                });

            modelBuilder.Entity("NimbusApi.Models.GpEndereco", b =>
                {
                    b.Property<int>("IdGpEndereco")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(10)")
                        .HasColumnName("id_gp_endereco");

                    OraclePropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdGpEndereco"));

                    b.Property<int>("IdEndereco")
                        .HasColumnType("NUMBER(10)");

                    b.Property<int>("IdUsuario")
                        .HasColumnType("NUMBER(10)");

                    b.Property<string>("NmGrupo")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("NVARCHAR2(100)");

                    b.HasKey("IdGpEndereco");

                    b.HasIndex("IdEndereco");

                    b.HasIndex("IdUsuario");

                    b.ToTable("t_nimbus_gp_endereco", (string)null);
                });

            modelBuilder.Entity("NimbusApi.Models.Localizacao", b =>
                {
                    b.Property<int>("IdLocalizacao")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(10)")
                        .HasColumnName("id_localizacao");

                    OraclePropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdLocalizacao"));

                    b.Property<string>("Latitude")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("NVARCHAR2(50)");

                    b.Property<string>("Longitude")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("NVARCHAR2(50)");

                    b.HasKey("IdLocalizacao");

                    b.ToTable("t_nimbus_localizacao", (string)null);
                });

            modelBuilder.Entity("NimbusApi.Models.Pais", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(10)")
                        .HasColumnName("id_pais");

                    OraclePropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("NomePais")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("NVARCHAR2(100)");

                    b.HasKey("Id");

                    b.ToTable("t_nimbus_pais", (string)null);
                });

            modelBuilder.Entity("NimbusApi.Models.Previsao", b =>
                {
                    b.Property<int>("IdPrevisao")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(10)")
                        .HasColumnName("id_previsao");

                    OraclePropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdPrevisao"));

                    b.Property<int>("Chuva")
                        .HasColumnType("NUMBER(10)")
                        .HasColumnName("chuva");

                    b.Property<int>("CodigoChuva")
                        .HasColumnType("NUMBER(10)")
                        .HasColumnName("codigo_chuva");

                    b.Property<DateTime>("DataHora")
                        .HasColumnType("TIMESTAMP(7)")
                        .HasColumnName("data_hora");

                    b.Property<int>("IdBairro")
                        .HasColumnType("NUMBER(10)");

                    b.Property<int>("RajadaVento")
                        .HasColumnType("NUMBER(10)")
                        .HasColumnName("rajada_vento");

                    b.Property<int>("Temperatura")
                        .HasColumnType("NUMBER(10)")
                        .HasColumnName("temperatura");

                    b.Property<int>("Umidade")
                        .HasColumnType("NUMBER(10)")
                        .HasColumnName("umidade");

                    b.Property<int>("VelocidadeVento")
                        .HasColumnType("NUMBER(10)")
                        .HasColumnName("velocidade_vento");

                    b.HasKey("IdPrevisao");

                    b.HasIndex("IdBairro");

                    b.ToTable("t_nimbus_previsao", (string)null);
                });

            modelBuilder.Entity("NimbusApi.Models.Usuario", b =>
                {
                    b.Property<int>("IdUsuario")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(10)")
                        .HasColumnName("id_usuario");

                    OraclePropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdUsuario"));

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("NVARCHAR2(100)");

                    b.Property<int?>("LocalizacaoIdLocalizacao")
                        .HasColumnType("NUMBER(10)");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("NVARCHAR2(100)");

                    b.Property<string>("Senha")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("NVARCHAR2(100)");

                    b.Property<int>("idLocalizacao")
                        .HasColumnType("NUMBER(10)");

                    b.HasKey("IdUsuario");

                    b.HasIndex("LocalizacaoIdLocalizacao");

                    b.ToTable("t_nimbus_usuario", (string)null);
                });

            modelBuilder.Entity("NimbusApi.Models.Alerta", b =>
                {
                    b.HasOne("NimbusApi.Models.Bairro", "Bairro")
                        .WithMany("Alertas")
                        .HasForeignKey("IdBairro")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Bairro");
                });

            modelBuilder.Entity("NimbusApi.Models.Bairro", b =>
                {
                    b.HasOne("NimbusApi.Models.Cidade", "Cidade")
                        .WithMany()
                        .HasForeignKey("IdCidade")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("NimbusApi.Models.Localizacao", "Localizacao")
                        .WithMany()
                        .HasForeignKey("IdLocalizacao")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Cidade");

                    b.Navigation("Localizacao");
                });

            modelBuilder.Entity("NimbusApi.Models.Cidade", b =>
                {
                    b.HasOne("NimbusApi.Models.Estado", "Estado")
                        .WithMany()
                        .HasForeignKey("IdEstado")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Estado");
                });

            modelBuilder.Entity("NimbusApi.Models.Endereco", b =>
                {
                    b.HasOne("NimbusApi.Models.Bairro", "Bairro")
                        .WithMany("Enderecos")
                        .HasForeignKey("IdBairro")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Bairro");
                });

            modelBuilder.Entity("NimbusApi.Models.Estado", b =>
                {
                    b.HasOne("NimbusApi.Models.Pais", "Pais")
                        .WithMany()
                        .HasForeignKey("IdPais")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Pais");
                });

            modelBuilder.Entity("NimbusApi.Models.GpEndereco", b =>
                {
                    b.HasOne("NimbusApi.Models.Endereco", "Endereco")
                        .WithMany()
                        .HasForeignKey("IdEndereco")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("NimbusApi.Models.Usuario", "Usuario")
                        .WithMany()
                        .HasForeignKey("IdUsuario")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Endereco");

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("NimbusApi.Models.Previsao", b =>
                {
                    b.HasOne("NimbusApi.Models.Bairro", "Bairro")
                        .WithMany("Previsao")
                        .HasForeignKey("IdBairro")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Bairro");
                });

            modelBuilder.Entity("NimbusApi.Models.Usuario", b =>
                {
                    b.HasOne("NimbusApi.Models.Localizacao", "Localizacao")
                        .WithMany()
                        .HasForeignKey("LocalizacaoIdLocalizacao");

                    b.Navigation("Localizacao");
                });

            modelBuilder.Entity("NimbusApi.Models.Bairro", b =>
                {
                    b.Navigation("Alertas");

                    b.Navigation("Enderecos");

                    b.Navigation("Previsao");
                });
#pragma warning restore 612, 618
        }
    }
}
